---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates(Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

    - name: instal Elastik  Stack (Ubuntu)
      apt:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install Elastik Stack (CentOS)
      dnf:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

